from __future__ import annotations
from enum import Enum

class NoTradeReason(str, Enum):
    # Tier 0 / constitution / gates
    DVS_TOO_LOW = "DVS_TOO_LOW"
    EQS_TOO_LOW = "EQS_TOO_LOW"
    KILL_SWITCH_ACTIVE = "KILL_SWITCH_ACTIVE"
    VOL_SHOCK_LOCKOUT = "VOL_SHOCK_LOCKOUT"
    SPREAD_SLIPPAGE_LOCKOUT = "SPREAD_SLIPPAGE_LOCKOUT"
    NEWS_LOCKOUT = "NEWS_LOCKOUT"
    IN_POSITION = "IN_POSITION"
    DAILY_LOSS_LIMIT = "DAILY_LOSS_LIMIT"
    WEEKLY_LOSS_LIMIT = "WEEKLY_LOSS_LIMIT"
    COOLDOWN_ACTIVE = "COOLDOWN_ACTIVE"
    SESSION_WINDOW_BLOCK = "SESSION_WINDOW_BLOCK"
    SESSION_NOT_TRADABLE = "SESSION_NOT_TRADABLE"
    SPREAD_TOO_WIDE = "SPREAD_TOO_WIDE"
    CONDITION_NOT_MET = "CONDITION_NOT_MET"
    MISSING_REQUIRED_SIGNAL = "MISSING_REQUIRED_SIGNAL"
    MAX_TRADES_REACHED = "MAX_TRADES_REACHED"
    CONSECUTIVE_LOSS_LOCKOUT = "CONSECUTIVE_LOSS_LOCKOUT"

    # Template / edge
    TEMPLATE_NOT_ALLOWED_BY_TIER = "TEMPLATE_NOT_ALLOWED_BY_TIER"
    STOP_EXCEEDS_RISK_BUDGET = "STOP_EXCEEDS_RISK_BUDGET"
    FRICTION_TOO_HIGH = "FRICTION_TOO_HIGH"
    BELIEF_TOO_LOW = "BELIEF_TOO_LOW"
    STABILITY_NOT_MET = "STABILITY_NOT_MET"
    EDGE_SCORE_BELOW_THETA = "EDGE_SCORE_BELOW_THETA"
    CLEAR_LEVEL_NOT_PRESENT = "CLEAR_LEVEL_NOT_PRESENT"

class SystemEvent(str, Enum):
    KILL_SWITCH = "KILL_SWITCH"
    HALT = "HALT"
    RESUME = "RESUME"
    DESYNC_DETECTED = "DESYNC_DETECTED"
